name: flutter_wallpaper_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  cached_network_image: ^3.3.0
  dio: ^5.3.3
  permission_handler: ^11.0.1
  flutter_cache_manager: ^3.3.1
  async_wallpaper: ^2.0.3
  google_fonts: ^6.1.0
  palette_generator: ^0.3.3+3
  flutter_dotenv: ^5.1.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_native_splash: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/.env
